<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?><!DOCTYPE html>
<html dir="ltr" lang="en-US"><!-- developed by r. anggit herdianto --><!-- email : anggitherdianto@gmail.com -->
   <head><meta charset="utf-8">
      <title><?php echo $judul?> - <?php echo setting('web_judul');?> - <?php echo setting('sekolah_nama');?></title>
      <meta name="viewport" content="initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no, width = device-width">
      <link rel="shortcut icon" href="<?php echo view_folder('u', 'favicon.ico');?>" type="image/x-icon">
      <link rel="stylesheet" type="text/css" href="<?php echo view_folder('u', 'style.css');?>" media="screen">
      <link rel="stylesheet" type="text/css" href="<?php echo view_folder('u', 'style.responsive.css');?>" media="all">
      <!--[if lte IE 7]><link rel="stylesheet" href="<?php echo view_folder('u', 'style.ie7.css');?>" media="screen" /><![endif]-->
      <script type="text/javascript" src="<?php echo view_external('jquery', 'jquery.min.js'); ?>"></script>
      <script type="text/javascript" src="<?php echo view_folder('u', 'script.js'); ?>"></script>
      <script type="text/javascript" src="<?php echo view_folder('u', 'script.responsive.js'); ?>"></script>
      <script type="text/javascript"> function sidebarStyle(){var e=$("html").height()-158+"px";$("#sidebarStyle").css("height",e)}function navStyle(){var e=$("html").width();if(e<=750){$("#navStyle").css("padding-top","0px")}else{$("#navStyle").css("padding-top","32px")}}$(document).ready(sidebarStyle);$(window).resize(sidebarStyle);$(document).ready(navStyle);$(window).resize(navStyle)</script>
      <!--[if lt IE 9]><script type="text/javascript" src="<?php echo view_folder('u', 'html5.js'); ?>"></script><![endif]-->
      <style> .content .postcontent-0 .layout-item-0{color:#303F50;padding-right:10px;padding-left:10px}.content .postcontent-0 .layout-item-1{margin-bottom:10px}.content .postcontent-0 .layout-item-2{border-spacing:10px 0;border-collapse:separate}.content .postcontent-0 .layout-item-3{border-style:Solid;border-width:1px;border-color:#EBE300;color:#1D2630;background:#FFFDD1;padding-right:10px;padding-left:10px}.content .postcontent-0 .layout-item-4{border-style:Solid;border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-color:#B92B18;color:#1D2630;background:#FEE4D7;padding-right:10px;padding-left:10px}.content .postcontent-0 .layout-item-5{border-style:Solid;border-top-width:1px;border-right-width:1px;border-bottom-width:1px;border-left-width:1px;border-color:#05A322;color:#1D2630;background:#EBFFD7;padding-right:10px;padding-left:10px}.content .postcontent-0 .layout-item-6{border-right-style:dotted;border-right-width:1px;border-right-color:#7993AF;color:#303F50;padding-right:10px;padding-left:10px}.ie6 .post .layout-cell,.ie7 .post .layout-cell{border:0!important;padding:0!important}.content .postcontent-0 .layout-item-table-1{vertical-align:top;padding-top:5px;padding-right:5px;padding-bottom:5px;padding-left:5px;border-top-width:0;border-right-width:0;border-bottom-width:0;border-left-width:0}</style>